version: "3.9"

services:
  apigateway :
    build : 
      context: .
      dockerfile: Dockerfile.Ocelot
    container_name: capygram-gateway
    ports:
      - "8088:8088"
      - "8090:8090"
    environment :
      - ASPNETCORE_HTTP_PORTS=8088
      - ASPNETCORE_HTTPS_PORTS=8090
      - ASPNETCORE_URLS=https://+:8090;http://+:8088
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    networks:
      - capygram-be-cicd_default
    user: "root:root"
    depends_on:
      - rabbitmq
      - neo4j
      - cassandra
      - mongodb
    restart: always

  auth :
    build : 
      context: .
      dockerfile: Dockerfile.Auth
    container_name: capygram-auth
    ports:
      - "8087:8087"
    environment :
      ASPNETCORE_HTTP_PORTS: 8087
    networks:
      - capygram-be-cicd_default
    depends_on:
      - rabbitmq
      - neo4j
      - cassandra
      - mongodb
    restart: always

  notification :
    build : 
      context: .
      dockerfile: Dockerfile.Notification
    container_name: capygram-notification
    ports:
      - "8082:8082"
    environment :
      ASPNETCORE_HTTP_PORTS: 8082
    networks:
      - capygram-be-cicd_default
    depends_on:
      - rabbitmq
      - neo4j
      - cassandra
      - mongodb
    restart: always

  graph :
    build : 
      context: .
      dockerfile: Dockerfile.Graph
    container_name: capygram-graph
    ports:
      - "8085:8085"
    environment :
      ASPNETCORE_HTTP_PORTS: 8085
    networks:
      - capygram-be-cicd_default
    depends_on:
      - rabbitmq
      - neo4j
      - cassandra
      - mongodb
    restart: always

  media :
    build : 
      context: .
      dockerfile: Dockerfile.Media
    container_name: capygram-media
    ports:
      - "8084:8084"
    environment :
      ASPNETCORE_HTTP_PORTS: 8084
    networks:
      - capygram-be-cicd_default
    depends_on:
      - rabbitmq
      - neo4j
      - cassandra
      - mongodb
    restart: always

  chat :
    build : 
      context: .
      dockerfile: Dockerfile.Chat
    container_name: capygram-chat
    ports:
      - "8083:8083"
    environment :
      ASPNETCORE_HTTP_PORTS: 8083
    networks:
      - capygram-be-cicd_default
    depends_on:
      - rabbitmq
      - neo4j
      - cassandra
      - mongodb
    restart: always

  post :
    build : 
      context: .
      dockerfile: Dockerfile.Post
    container_name: capygram-post
    ports:
      - "8081:8081"
    environment :
      ASPNETCORE_HTTP_PORTS: 8081
    networks:
      - capygram-be-cicd_default
    depends_on:
      - rabbitmq
      - neo4j
      - cassandra
      - mongodb
    restart: always

  newsfeed :
    build : 
      context: .
      dockerfile: Dockerfile.Newsfeed
    container_name: capygram-newsfeed
    ports:
      - "8086:8086"
    environment :
      ASPNETCORE_HTTP_PORTS: 8086
    networks:
      - capygram-be-cicd_default
    depends_on:
      - rabbitmq
      - neo4j
      - cassandra
      - mongodb
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "capygram"
    networks:
      - capygram-be-cicd_default
    restart: always

  neo4j:
    container_name: neo4j
    image: neo4j:4.4.10
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/hieu1234
      NEO4J_dbms_default__database: neo4j
    volumes:
      - neo4j_data:/data
    networks:
      - capygram-be-cicd_default
    restart: always

  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - capygram-be-cicd_default
    restart: always

  mongodb:
    container_name: mongodb
    image : mongo:4.4.18
    environment:
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - capygram-be-cicd_default
    restart: always

  redis:
    container_name: redis 
    image : redis:latest  
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - capygram-be-cicd_default
    restart: always

volumes:
  neo4j_data:
    driver: local
  cassandra_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  capygram-be-cicd_default:
    driver: bridge
